server:
  port: 8082
spring:
  application:
    name: springcloud-microservice-study-service-order
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5

### springcloud-eureka 默认开始支持ribbon
ribbon:
  ###指的是建立连接后，从服务器读到可用数据的时间
  ReadTimeout: 5000
  ###指的是建立连接所用的时间
  ConnectTimeout: 1400
### 开启hystrix断路器
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500





