spring:
  application:
    name: springcloud-microservice-study-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinyuxin/springcloud-config.git
          search-paths:
          - '{application}'
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
      fetch-registry: true
      register-with-eureka: true
server:
  port: 8081
