### 服务端口地址
server:
  port: 8080


eureka:
  instance:
    ###注册中心地址
    hostname: 127.0.0.1
  server:
  ### 测试和开发环境关闭自我保护机制，保证服务不可用时 及时退出
    enable-self-preservation: false
    ### 每2秒检查一次
    eviction-interval-timer-in-ms: 5000
  client:
    service-url:
      ### 注册地址
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
    ### 因为自己是注册中心，不需要去检索服务信息
    fetch-registry: false
    ### 因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群的时候需要设置为true）
    register-with-eureka: false
spring:
  application:
    name: springcloud-study-eureka


