## 会员项目的端口号
server:
  port: 8082

## 服务别名，服务注册到eureka的名称
spring:
  application:
    name: springcloud-study-member

eureka:
  instance:
    ###心跳检测和续约时间，测试开发阶段，值尽量设置小一些，保证服务关闭后，注册中心能及时踢出服务
    lease-renewal-interval-in-seconds: 2
    ### eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒。超过则踢出
    lease-expiration-duration-in-seconds: 3
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    fetch-registry: true
    register-with-eureka: true
